### ISSUE TITLE
Make game crash

### ISSUE THREAD

**Issue by Trululuexe** [Sharlottes/Informatis#100]
Just cannot launch the game it crash instantly

**Comment by Trululuexe** [comment]
[crash-report-09_09_2023_17_06_40.txt](https://github.com/Sharlottes/Informatis/files/12566095/crash-report-09_09_2023_17_06_40.txt)

**Comment by Sharlottes** [comment]
scheme-size mod crashed the Informatis by removing `tags` field.

**Comment by Sharlottes** [comment]
@Trululuexe did you really read that mod description?
![image](https://github.com/Sharlottes/Informatis/assets/60801210/b4984879-cdc8-4b67-a6d0-1c796b8c3898)

check the latest hotfix release

**Comment by Sharlottes** [comment]
due to this issue being too old and the reporter no longer responding, the issue is closed now.
