### ISSUE TITLE
Got a crash when playing Darkdustry - Attack

### ISSUE THREAD

**Issue by HiKE-yt** [Sharlottes/Informatis#64]
![image](https://user-images.githubusercontent.com/68474172/187916418-61a338a8-dd90-4936-88fc-d1748a46b1dd.png)
[crash-report-09_01_2022_14_32_20.txt](https://github.com/Sharlottes/Informatis/files/9469821/crash-report-09_01_2022_14_32_20.txt)

**Comment by Sharlottes** [comment]
https://github.com/Sharlottes/Informatis/actions/runs/3124751675
can you use this latest action build and try again?
