### ISSUE TITLE
"No JAR file found in releases" error - 144.3

### ISSUE THREAD

**Issue by KnightGabriel** [Sharlottes/Informatis#77]
When I try to download the latest version of this mod(1.8), I get this message: "No JAR file found in releases. Make sure you have a valid jar file in the mod's latest Github Release". What am I supposed to do?

**Comment by KnightGabriel** [comment]
@Sharlottes Please help

**Comment by Sharlottes** [comment]
oh no sorry, I posted "zip" file into release. i fixed it - you can try again, or also can download the mod file directly!
https://github.com/Sharlottes/Informatis/releases/tag/v1.8
