### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by Sector171** [Sharlottes/Informatis#78]
Hi,

The mod still not working on mobile (Android), even after the last fix.
The game crashes at startup.

Thanks.

**Comment by Slotterleet** [comment]
Hi,

You haven't sent the crash report.
The game crashes at startup.

Thanks.

**Comment by Sector171** [comment]
Ah sorry, this is the crash report:

Mindustry has crashed. How unfortunate.
Version: release build 144.3
OS: Linux xnull (aarch64)
Android API level: 27
Java Version: 0
Runtime Available Memory: 256mb
Cores: 8
Mods: informatis:1.8

> NoClassDefFoundError: 'Failed resolution of: Ljava/lang/Iterable$-CC;'
ObjectMap$MapIterator.forEach: 0
OverDraws.eachDraws: 82
OverDraws.lambda$init$8: 67
-$$Lambda$OverDraws$L8fQKENqjmm6uK3dVJVu07hNHf8.run: 0
Events.lambda$run$2: 0
Events.$r8$lambda$r1ZaaGUtG03In-r__kf9lAmJrDc: 0
Events$$ExternalSyntheticLambda0.get: 40
Events.fire: 4
Logic.update: 1
ApplicationCore.update: 2
ClientLauncher.update: 17
AndroidGraphics.onDrawFrame: 22
GLSurfaceView$GLThread.guardedRun: 793
GLSurfaceView$GLThread.run: 27
> ClassNotFound: 'Didn't find class "java.lang.Iterable$-CC" on path: DexPathList[[zip file "/data/app/io.anuke.mindustry-_V8qOKjbQ44eQbHKgFPj3A==/base.apk"],nativeLibraryDirectories=[/data/app/io.anuke.mindustry-_V8qOKjbQ44eQbHKgFPj3A==/lib/arm64, /data/app/io.anuke.mindustry-_V8qOKjbQ44eQbHKgFPj3A==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]'
BaseDexClassLoader.findClass: 125
ClassLoader.loadClass: 379
ClassLoader.loadClass: 312
ObjectMap$MapIterator.forEach: 0
OverDraws.eachDraws: 82
OverDraws.lambda$init$8: 67
-$$Lambda$OverDraws$L8fQKENqjmm6uK3dVJVu07hNHf8.run: 0
Events.lambda$run$2: 0
Events.$r8$lambda$r1ZaaGUtG03In-r__kf9lAmJrDc: 0
Events$$ExternalSyntheticLambda0.get: 40
Events.fire: 4
Logic.update: 1
ApplicationCore.update: 2
ClientLauncher.update: 17
AndroidGraphics.onDrawFrame: 22
GLSurfaceView$GLThread.guardedRun: 793
GLSurfaceView$GLThread.run: 27

**Comment by Sharlottes** [comment]
checked. i'm fixing

**Comment by Sharlottes** [comment]
[v1.8.1](https://github.com/Sharlottes/Informatis/releases/tag/v1.8.1) has been Released to hotfix & v145 version up
