### ISSUE TITLE
Not working well

### ISSUE THREAD

**Issue by Sector171** [Sharlottes/Informatis#81]
Hi,
No more crash at startup but the mod is not working well.
First there is big lag. This mod before the last main mindustry update was so smooth and player-friendly. With this lag....no way.

Second it is not working, the windows not showing the elements properly as shown in the picture.
![Screenshot_2023-06-27-14-30-29-977_io anuke mindustry](https://github.com/Sharlottes/Informatis/assets/77055524/067b4c04-fa4c-4560-939f-091d4b67109f)

Also i noticed that after the startup exactly before showing the menu, that flash still exist, before the last fix after this flash there was crash, now there is no crash but huge lag and the mod not working. Apparently there is big problem in your code.

Mobile-Android

**Comment by Sharlottes** [comment]
i really have no time to check out the mod anymore, it will take a long time...

**Comment by Sharlottes** [comment]
@Sector171 can you check below action's artifact?
https://github.com/Sharlottes/Informatis/actions/runs/5985658462

**Comment by Sector171** [comment]
Hi,
Fast check, it looks fine thanks.
But it was a fast test, if later i find anything i will inform you.

**Comment by Sharlottes** [comment]
thanks for your reply although I'm too late to respond.
if you find a new issue or have any recommendation ideas, please post a new issue.
